name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to trigger manual jobs
        required: false
        default: ''
jobs:
  jdk-8-01-jersey-maven-archetype:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    env:
      JAVA_VERSION: 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/io/github/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - run: ./mvnw -f 01-jersey-maven-archetype -Djava.version=1.8
  jdk-11-8-01-jersey-maven-archetype:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    env:
      JAVA_VERSION: 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/io/github/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - run: ./mvnw -f 01-jersey-maven-archetype -Djava.version=1.8
  jdk-11-11-01-jersey-maven-archetype:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    env:
      JAVA_VERSION: 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/io/github/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - run: ./mvnw -f 01-jersey-maven-archetype -Djava.version=11
  jdk-17-8-01-jersey-maven-archetype:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    env:
      JAVA_VERSION: 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/io/github/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - run: ./mvnw -f 01-jersey-maven-archetype -Djava.version=1.8
  jdk-17-11-01-jersey-maven-archetype:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    env:
      JAVA_VERSION: 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/io/github/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - run: ./mvnw -f 01-jersey-maven-archetype -Djava.version=11
  jdk-17-17-01-jersey-maven-archetype:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    env:
      JAVA_VERSION: 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/io/github/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - run: ./mvnw -f 01-jersey-maven-archetype -Djava.version=17
#  jdk-21-8-jersey-maven-archetype:
#    if: github.event.inputs.trigger == ''
#      || !startsWith(github.event.inputs.trigger, 'm')
#      || !startsWith(github.event.inputs.trigger, 'M')
#    env:
#      JAVA_VERSION: 21
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
#          distribution: 'temurin'
#          java-version: ${{ env.JAVA_VERSION }}
#      - uses: actions/cache@v3
#        with:
#          path: |
#            ~/.m2/repository
#            !~/.m2/repository/io/github/daggerok
#          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
#      - run: ./mvnw -f 01-jersey-maven-archetype -Djava.version=1.8
#  jdk-21-11-jersey-maven-archetype:
#    if: github.event.inputs.trigger == ''
#      || !startsWith(github.event.inputs.trigger, 'm')
#      || !startsWith(github.event.inputs.trigger, 'M')
#    env:
#      JAVA_VERSION: 21
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
#          distribution: 'temurin'
#          java-version: ${{ env.JAVA_VERSION }}
#      - uses: actions/cache@v3
#        with:
#          path: |
#            ~/.m2/repository
#            !~/.m2/repository/io/github/daggerok
#          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
#      - run: ./mvnw -f 01-jersey-maven-archetype -Djava.version=11
#  jdk-21-17-jersey-maven-archetype:
#    if: github.event.inputs.trigger == ''
#      || !startsWith(github.event.inputs.trigger, 'm')
#      || !startsWith(github.event.inputs.trigger, 'M')
#    env:
#      JAVA_VERSION: 21
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
#          distribution: 'temurin'
#          java-version: ${{ env.JAVA_VERSION }}
#      - uses: actions/cache@v3
#        with:
#          path: |
#            ~/.m2/repository
#            !~/.m2/repository/io/github/daggerok
#          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
#      - run: ./mvnw -f 01-jersey-maven-archetype -Djava.version=17
